### PR TITLE
Add idea for acceptance testing

### PR DESCRIPTION
**Pull request by tomphp**
What do you think of this?

My idea would be to eventually replace the existing tests with this. It works in a similar way to the existing tests but I think there's too much logic in there. Also they're not explicit, there's an input file and an expected output file but no explanation why. Using these tests we can actually document the behaviour of the app.

Let me know what you think, if you're good to go I'll test every case I can think of.

### CODE REVIEW

**Comment by gianarb** [comment]
In my opinion this is a good refactoring but in this moment I have a problem to try this patch.. In my opinion now the tests are more readable :+1:

**Comment by tomphp** [comment]
Are you having problems running it? I updated the autoloader so a maybe you
need to run a composer update

Are you happy for me to add the other tests? I'll make sure everything in
the original test suite is covered (and more)

**Comment by tomphp** [comment]
This now contains what I believe to be all the tests which the original test suite covers, plus a few more. There are some things which I still could do to tidy it, plus a whole load more possible tests (e.g. all the command line arguments). It's also highlighted a few bugs (tests marked as incomplete - I will submit some PRs).

Do you think these are worthwhile? If these are considered a decent improvement then there is no need to keep the original tests.

Once the suite is running I would be good to start getting the PRs in before working any more on the codebase I think.

**Comment by gianarb** [comment]
Perfect! In my opinion this is a good improvement I merge it and ping techlivezheng for your opinion about it :) 

Thanks for this refactoring!

**Pull request merged**
